In [3]:
from dtmapi import get_idp_admin0_data

# Get IDP Admin 0 Data for Ethiopia from Round 1 to Round 10
idp_admin0_data = get_idp_admin0_data(CountryName='Ethiopia', FromRoundNumber=1, ToRoundNumber=10, to_pandas=True)
idp_admin0_data.head()

,id,operation,admin0Name,admin0Pcode,numPresentIdpInd,reportingDate,yearReportingDate,monthReportingDate,roundNumber,assessmentType
0,824,Countrywide monitoring,Ethiopia,ETH,1696145,2017-12-31T00:00:00,2017,12,8,SA
1,148,Countrywide monitoring,Ethiopia,ETH,1742461,2018-02-28T00:00:00,2018,2,9,SA
2,834,Countrywide monitoring,Ethiopia,ETH,1613436,2018-04-30T00:00:00,2018,4,10,SA
3,869,Ethiopia - Gedeo and West Guji Rapid Response,Ethiopia,ETH,359113,2018-07-30T00:00:00,2018,7,1,SA
4,293,Northern Ethiopia Crisis,Ethiopia,ETH,131590,2021-01-31T00:00:00,2021,1,2,SA